unordered_map_hash:unordered_map_hash.cpp
	g++ unordered_map_hash.cpp -o unordered_map_hash -std=c++17

unordered_map_hash_v2:unordered_map_hash_v2.cpp
	g++ unordered_map_hash_v2.cpp -o unordered_map_hash_v2 -std=c++17