server: server.cpp
	g++ server.cpp -o server
client: client.cpp
	g++ client.cpp -o client
alarm: alarm_test.cpp
	g++ alarm_test.cpp -o alarm
alarm_adv: setitimer_test.cpp
	g++ setitimer_test.cpp -o alarm_adv
alarm_adv2: setitimer_test2.cpp
	g++ setitimer_test2.cpp -o alarm_adv2