local_socket_test: local_socket.cpp
	g++ local_socket.cpp -o local_socket_test
local_socket_client_test: local_socket_client.cpp
	g++ local_socket_client.cpp -o local_socket_client_test
udp_server_test: udp_server.cpp
	g++ udp_server.cpp -o udp_server_test
udp_client_test: udp_client.cpp
	g++ udp_client.cpp -o udp_client_test