mmap_test: mmap.cpp
	g++ mmap.cpp -o mmap_test
pipe_test: pipe_test.cpp
	g++ pipe_test.cpp -o pipe_test
basic_io_test: basic_io.cpp
	g++ basic_io.cpp -o basic_io_test
fifo_r: fifo_read.cpp
	g++ fifo_read.cpp -o fifo_r
fifo_w: fifo_write.cpp
	g++ fifo_write.cpp -o fifo_w

testa:	testa.c
	gcc testa.c -o testa
testbc:	testbc.c
	gcc testbc.c -o testbc
two_pipe:	two_pipe.c
	gcc two_pipe.c -o two_pipe